#6 Feat: Project setup
alisherj0n/rocket pull request #18
Opened 2022-04-03 23:26 UTC by alisherj0n

2022-04-04 11:13 UTC, AzamatRasulov requested changes

2022-04-04 11:13 UTC, AzamatRasulov commented on style/base.css
> +  font-family: "Inter", sans-serif;
С чего ты взял?

2022-04-04 11:13 UTC, AzamatRasulov commented on style/base.css
> +  color: var(--color-muted);
Неправильный цвет

2022-04-04 11:13 UTC, AzamatRasulov commented on style/bundle.css
> +@import url(./typography.css);
Неправильный порядок

2022-04-04 11:13 UTC, AzamatRasulov commented on style/colors.css
> +  --color-warning-dark: #e56e19;
Почему dark только у одного цвета?

2022-04-04 11:13 UTC, AzamatRasulov commented on style/colors.css
> +  --color-charcoal: #595f69;
ОТкуда такое название?

2022-04-04 11:13 UTC, AzamatRasulov commented on style/colors.css
> +  --color-black: #3f434a;
Все-такие лучше использовать названия из макета. Так сам запутаешься.

2022-04-04 12:00 UTC, alisherj0n commented on style/base.css
> +  font-family: "Inter", sans-serif;
<img width="349" alt="image" src="https://user-images.githubusercontent.com/86313597/161539317-ed679df3-3c45-4dfc-9ab4-e8c57d04e0e1.png">

2022-04-04 13:02 UTC, alisherj0n commented on style/base.css
> +  color: var(--color-muted);
Поменял

2022-04-04 13:03 UTC, alisherj0n commented on style/colors.css
> +  --color-black: #3f434a;
Добавил все цвета и названия из макета

2022-04-04 18:34 UTC, AzamatRasulov commented on style/base.css
> +  font-family: "Inter", sans-serif;
🤦‍♂️. Ты фигму верстать собрался ?

2022-04-04 18:37 UTC, AzamatRasulov commented on style/base.css
> +  font-family: "Inter", sans-serif;
И зачем ты резолвишь мои ревью? Вопрос задал я, и я решаю, решена ли проблема.
![085096FC-C747-42FD-939D-71670801922C](https://user-images.githubusercontent.com/21981821/161609362-97314bc9-3d7b-4e16-9582-19ec30086b37.jpeg)

2022-04-04 18:41 UTC, AzamatRasulov requested changes

2022-04-04 18:41 UTC, AzamatRasulov commented on style/base.css
> +  color: var(--color-heading);
Все ещё не тот цвет

2022-04-05 10:29 UTC, AzamatRasulov requested changes

2022-04-05 10:29 UTC, AzamatRasulov commented on style/base.css
> +  color: var(--color-body-light);
Уже ближе. Но все еще не тот.

2022-04-05 10:29 UTC, AzamatRasulov commented on style/typography.css
> +}
В смысле? У тебя для текста самый часто используемый тег – p. Зачем ты дал тексту общий цвет один, а потом пришел и сюда дал почти тоже самый общий цвет – но уже другой? Создал проблему и ее решил?

2022-04-05 12:46 UTC, alisherj0n commented on style/base.css
> +  color: var(--color-body-light);
Поменял цвет

2022-04-05 12:46 UTC, alisherj0n commented on style/typography.css
> +}
Удалил цвета для этих тегов

2022-04-05 16:42 UTC, AzamatRasulov approved these changes

2022-04-05 16:42 UTC, merged