#5 Feat: Common sidebar
alisherj0n/rocket pull request #20
Opened 2022-04-07 09:58 UTC by alisherj0n

2022-04-09 10:57 UTC, AzamatRasulov requested changes

2022-04-09 10:57 UTC, AzamatRasulov commented on index.html
> +          <img src="./images/Rocket.png" alt="App logo" class="logo" />
`alt` должен описывать что конкретно на фото

2022-04-09 10:57 UTC, AzamatRasulov commented on index.html
> +          <h6 class="heading">Rocket</h6>
Почему это заголовок? Лого никогда не пишется буквами.

2022-04-09 10:57 UTC, AzamatRasulov commented on index.html
> +        </li>
Нормально закрой

2022-04-09 10:57 UTC, AzamatRasulov commented on index.html
> +            >
Не закрыл. Чиба ма кори вскоду приттиера кадестам, додар?

2022-04-09 10:57 UTC, AzamatRasulov commented on index.html
> +          <li class="items">
Почему здесь `items`?

2022-04-09 10:57 UTC, AzamatRasulov commented on index.html
> +            ><img src="./style/icons/Cart.svg" alt="" class="icon" />
`alt` не может быть пустым

2022-04-09 10:57 UTC, AzamatRasulov commented on index.html
> +              <span class="indicator"></span>
Что будет, если я захочу сделать активным другой пункт меню?

2022-04-09 10:57 UTC, AzamatRasulov commented on index.html
> +            >
Чтобы вот такой хуйни небыло, скопируй файл `.prettierrc` из прошлого проекта

2022-04-09 10:57 UTC, AzamatRasulov commented on style/base.css
> +  color: var(--color-heading);
Ссылки среди текста должны выделяться. Обычно ссылки красят в `primary`.

2022-04-09 10:57 UTC, AzamatRasulov commented on style/bundle.css
> +@import url(./components/icons.css);
wtf?

2022-04-09 10:57 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  flex-direction: column;
Зачем?

2022-04-09 10:57 UTC, AzamatRasulov commented on style/components/sidebar.css
> +}
Зачем? Лого должно быть одной картинкой.

2022-04-09 10:57 UTC, AzamatRasulov commented on style/components/sidebar.css
> +.sidebar .items {
Что такое sidebar items?

2022-04-09 10:57 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  gap: 1rem;
Ту мач флекс. Где-то что-то лишнее.

2022-04-09 10:57 UTC, AzamatRasulov commented on index.html
> +          </button>
Это делается не так. Тут иконка – не кнопка, а чисто индикатор того, что в этом пункте меню скрыты другие. При нажатии на ВЕСЬ такой пункт – открывается подменю.

2022-04-09 10:57 UTC, AzamatRasulov commented on style/components/sidebar.css
> +}
Лишнее

2022-04-09 10:57 UTC, AzamatRasulov commented on style/components/sidebar.css
> +}
Это не должно быть здесь

2022-04-09 10:57 UTC, AzamatRasulov commented on style/components/sidebar.css
> +}
Да и сверстано неправильно.

2022-04-09 10:57 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  padding-left: 1.9rem;
Бред. Ты даешь паддинг на основании того, что пункт меню активный?

2022-04-09 10:57 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  left: -3px;
Бред

2022-04-09 10:57 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  width: 7px;
Бред

2022-04-09 10:57 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  .sidebar span,
ЛЮБОЙ `span` сайдбара будет скрыт?

2022-04-09 10:57 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  .sidebar .items.active {
`active` висит не там, где должен

2022-04-11 08:04 UTC, AzamatRasulov requested changes

2022-04-11 08:04 UTC, rasulovdev commented on index.html
> +          class="logo-only"
Что значит `logo` и `logo-only`? Может `icon-only`?

2022-04-11 08:04 UTC, rasulovdev commented on index.html
> +                <span class="heading">Dashboard</span>
Это не заголовок. Это просто текст ссылки.

2022-04-11 08:04 UTC, rasulovdev commented on style/base.css
> +  color: var(--color-accent);
Приведи полную цитату из моего прошлого коммента на счет цвета ссылок.

2022-04-11 08:04 UTC, rasulovdev commented on style/base.css
> +  color: var(--color-body-light);
Ты думаешь это выглядит хорошо?

2022-04-11 08:04 UTC, rasulovdev commented on style/components/notification.css
> +.notification {
https://bit.ly/3jq9yn9

2022-04-11 08:04 UTC, rasulovdev commented on style/components/notification.css
> +  line-height: 7px;
Не должно тут этого быть

2022-04-11 08:04 UTC, rasulovdev commented on style/components/sidebar.css
> +  opacity: 0;
Это еще что такое??

2022-04-11 08:04 UTC, rasulovdev commented on style/components/sidebar.css
> +  opacity: 0;
Я знаю, что делает `opacity: 0`.

2022-04-11 08:04 UTC, rasulovdev commented on style/components/sidebar.css
> +  cursor: pointer;
Зачем?

2022-04-11 08:04 UTC, rasulovdev commented on style/components/sidebar.css
> +  margin-right: -1.6rem;
Вот этого можно избежать

2022-04-11 08:04 UTC, rasulovdev commented on style/components/sidebar.css
> +.sidebar .nav .item div {
Нельзя выбирать по тегу.

2022-04-11 08:04 UTC, rasulovdev commented on style/components/sidebar.css
> +}
Полный бред. Посмотри на макет. Там размер текста меню меньше, чем в остальных местах?

2022-04-11 08:04 UTC, rasulovdev commented on style/components/sidebar.css
> +  position: relative;
такие вещи, как position, margin, padding не должны устанавливаться при условиях. Чем тебе не нравится поставить это в базовом классе?

2022-04-11 08:04 UTC, rasulovdev commented on style/components/sidebar.css
> +  .sidebar .nav .item.active::before {
Хорошо, согласен. А как тогда я узнаю, какой айтем активный на мленьком экране? Надо что-то придумать.

2022-04-11 08:04 UTC, rasulovdev commented on style/components/sidebar.css
> +  }
Технология верная, реализация – бред

2022-04-11 08:04 UTC, rasulovdev commented on style/components/sidebar.css
> +    border-radius: 15px;
Именно на `.active`?

2022-05-24 13:42 UTC, rasulovdev requested changes

2022-05-24 13:42 UTC, AzamatRasulov commented on style/components/sidebar.css
> +    background-color: var(--color-accent);
![image](https://user-images.githubusercontent.com/21981821/170041528-38803938-864c-4e80-b108-3fefee7fc9b9.png)

2022-05-24 13:42 UTC, AzamatRasulov commented on style/components/sidebar.css
> +@media (max-width: 992px) {
Широковат сайдбар. На мелких экранах занимает много места, можно поуже чуток.

![image](https://user-images.githubusercontent.com/21981821/170041790-d2ec1205-6e06-4e8b-8ded-e7e6a8af3f8b.png)

2022-05-24 13:42 UTC, rasulovdev commented on index.html
> +                </svg>
Давай поищем похожий айконпак или на крайняк font awesome. Так не очень

2022-05-24 13:42 UTC, AzamatRasulov commented on index.html
> +              <span class="notification-badge">8</span>
Почему именно `notification`? Если дальше где-то понадобится бейдж не в контексте уведомлений, что делать будешь?

2022-05-24 13:42 UTC, AzamatRasulov commented on index.html
> +              <div class="category">
От этого дива можно избавиться. Я вижу, зачем он, но можно оттолкнуть иконку и с помощью margin auto.

2022-05-24 13:42 UTC, AzamatRasulov commented on style/components/notification.css
> +  background-color: var(--color-red);
А если понадобится потом бейдж с другим фоном?

2022-05-24 13:42 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  padding: 0.9rem 1.6rem 0.7rem;
Какие-то странные значения. Нужно стараться писать ровные цифры

2022-05-24 13:42 UTC, AzamatRasulov commented on style/components/sidebar.css
> +.sidebar .icon-only {
Пропустил элемент, который должен быть icon-only

2022-05-24 13:42 UTC, rasulovdev commented on style/components/sidebar.css
> +  width: 9.5rem;
Для картинок обычно используют max-width, чтобы они не были больше необходимого, но не растягивались, если они меньше.

2022-05-24 13:42 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  width: 1.6rem;
А зачем указывать ширину, если на след строчке ты этот элемент скрываешь?

2022-05-24 13:42 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  background-color: var(--color-bg);
Эта переменная используется только в сайдбаре, но почему-то объявлена аж в `colors.css`. Кто-то может подумать, что эта переменная используется вообще где угодно для фона.

2022-05-24 13:42 UTC, AzamatRasulov commented on style/components/sidebar.css
> +    align-items: center;
Зачем это все тут нужно?

2022-05-24 13:42 UTC, AzamatRasulov commented on style/components/sidebar.css
> +    gap: 1rem;
Да и это тоже не нужно. Удали, и реши проблему по-другому.

2022-05-24 13:42 UTC, AzamatRasulov commented on style/components/sidebar.css
> +    gap: 1rem;
Отступами и margin auto, где нужно центрировать

2022-05-24 13:42 UTC, AzamatRasulov commented on style/layout.css
>  @media (max-width: 1200px) {
Ниже в этом файле, на строке 14 ты жестко задал ширину сайдбара. Так нельзя, сделай так, чтобы он был той ширины, сколько у него контента. Так ты сможешь это регулировать паддингами там в сайдбаре.

2022-05-24 13:42 UTC, AzamatRasulov commented on style/components/sidebar.css
> +    padding-right: 0.8rem;
А это еще почему? У тебя вроде должен получиться квадрат, так зачем там разные отступы

2022-05-24 13:42 UTC, AzamatRasulov commented on style/components/sidebar.css
> +    border-radius: 15px;
Предлагаю создать пачку переменных для закругления, по аналогии с брейкпоинтами:
```CSS
--border-radius: 1rem;
--border-radius-sm: calc(var(--border-radius) / 2);
--border-radius-xs: calc(var(--border-radius-sm) / 2);
```

И замени значения во всех `border-radius` на соответствующие переменные

2022-05-24 13:42 UTC, AzamatRasulov commented on style/components/sidebar.css
> +@media (max-width: 992px) {
Второе: вот у тебя теперь есть узкий сайдбар на меленьких экранах. Но у тебя в макете же есть еще и ситуация, когда экран большой, но сайдбар все равно там узкий. Этот момент как решишь?

2022-05-25 04:22 UTC, alisherj0n commented on index.html
> +              <span class="notification-badge">8</span>
Можешь пояснить, здесь нужно класс по другому назвать ?

2022-05-25 07:20 UTC, alisherj0n commented on style/components/sidebar.css
> +@media (max-width: 992px) {
На уме 2 варианта.

2022-05-26 12:26 UTC, AzamatRasulov commented on index.html
> +              <span class="material-icons-outlined icon additional-menu">
Это обычно называют не `additional-menu`, а `chevron-down`

2022-05-26 12:30 UTC, AzamatRasulov commented on style/bundle.css
> +@import url(./components/sidebar-collapsed.css);
Шарт нест отдельно файл кни. Компонент тот же.

2022-05-26 12:31 UTC, AzamatRasulov commented on style/components/sidebar-collapsed.css
> +.app.collapsed .sidebar .link-txt,
Ябора логорам хамича биер

2022-05-26 12:33 UTC, AzamatRasulov commented on style/components/sidebar-collapsed.css
> +  padding: 1rem 0;
Не нужен здесь паддинг. Здесь – только внешний отступ снизу в 1rem. Чтобы отодвинуть лого от верхней границы сайдбара, нужно делать внутренний отступ сверху/снизу самому сайдбару.

2022-05-26 12:35 UTC, AzamatRasulov commented on style/components/sidebar-collapsed.css
> +}
1. Одинаковые стили, почему не объединил?
2. На ховере должен быть тот же цвет, что и на ховере у большого сайдбара.

**Эти два коммента взаимоисключающие.** Первый просто показывает проблему. Если второй решишь, первый уже будет невалиден

2022-05-26 12:37 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  padding: 1rem 1.7rem 0.5rem;
Отступы слева/справа я еще понимаю, но нафига тут **внутренние** отступы сверху/снизу? Эта проблема решается не здесь

2022-05-26 12:37 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  padding: 1rem 1.7rem 0.5rem;
И да, отступы слева/справа должны быть такими же, как в меню, т.е. переиспользование, т.е. переменная

2022-05-26 12:38 UTC, AzamatRasulov commented on style/components/sidebar.css
> +}
Где-то это я уже видел

2022-05-26 12:40 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  margin: 0 0 0 auto;
ак намешид хамира дига хел кни?

2022-05-26 12:41 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  margin: 0 0 0 auto;
1. Не пиши так, если отступ нужен только с одной стороны.
2. Найди способ, при котором не придется отталкивать каждую новую икноку отдельно.

2022-05-26 12:43 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  background-color: var(--color-bg);
Эта переменная используется только в сайдбаре, но почему-то объявлена аж в `colors.css`. Кто-то может подумать, что эта переменная используется вообще где угодно для фона.

2022-05-27 05:47 UTC, AzamatRasulov requested changes

2022-05-27 05:47 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  --color-bg: #f8f8f8;
Именование должно быть одинаковым. Ты либо пиши название компонента (sidebar) во всех переменных, либо не пиши нигде

2022-05-27 05:47 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  border-left: 7px solid var(--color-accent);
Здесь был целый коммент на этот счет. Куда он делся? Найди, прочитай и исправь

2022-05-27 05:47 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  padding: 1.4rem 0.8rem;
Не так

2022-05-27 05:47 UTC, AzamatRasulov commented on style/components/sidebar.css
> +    padding: 1.4rem 0.6rem;
Вроде бы узкий сайдбар должен выглядеть одинаково что на маленьких экранах, что через класс, нет? Почему тогда у тебя через класс один отступ (строка 69), а через размер экрана – другой? Вот для этого и нужно использовать переменные.

2022-05-27 05:47 UTC, AzamatRasulov commented on style/components/sidebar.css
> +    padding: 0;
Вот этого нет в случае с классом. Значит оно и здесь не нужно?

2022-05-27 06:02 UTC, AzamatRasulov requested changes

2022-05-27 06:02 UTC, AzamatRasulov commented on style/components/sidebar.css
> +}
Блоки 41-44 и 51-54 идентичны.

2022-05-27 06:02 UTC, AzamatRasulov commented on style/components/sidebar.css
> +}
Это вообще лишнее

2022-05-27 06:02 UTC, AzamatRasulov commented on style/components/sidebar.css
> +}
у всех иконок цвет должен быть --color-body-light, не только у этой

2022-05-27 10:25 UTC, AzamatRasulov requested changes

2022-05-27 10:25 UTC, AzamatRasulov commented on style/components/notifications.css
> +.badge {
Имя файла не совпадает с названием компонента

2022-05-27 10:25 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  --sidebar-padding-collpased: 1.5rem 0.6rem;
Нафига две ? ПЕРЕМЕНные для того и нужны, чтобы в разных условиях МЕНЯЛИСЬ

2022-05-27 10:25 UTC, AzamatRasulov commented on style/components/sidebar.css
> +    padding: var(--sidebar-padding-collpased);
неправильно. Используй ту же перменную

2022-05-27 10:25 UTC, AzamatRasulov commented on style/components/sidebar.css
> +  border-left: 4px solid var(--color-accent);
Почти. Все то же самое, только не бордером

2022-05-27 10:25 UTC, AzamatRasulov commented on style/components/sidebar.css
> +.app.collapsed .sidebar .logo,
два раза

2022-05-27 10:25 UTC, AzamatRasulov commented on style/components/sidebar.css
> +/* -----------Sidebar-collapsed-------------- */
И вообще почему все в такой каше? У тебя одни и те же стили, просто применяются в разных условиях, отсортируй одинаково

2022-05-29 14:37 UTC, AzamatRasulov approved these changes

2022-05-29 14:37 UTC, merged

2022-05-29 14:38 UTC, AzamatRasulov commented
👏