#7 Feat: Project List > Page header
alisherj0n/rocket pull request #22
Opened 2022-06-01 11:34 UTC by alisherj0n

2022-06-29 18:08 UTC, rasulovdev requested changes

2022-06-29 18:08 UTC, rasulovdev commented on style/base.css
> +  color: inherit;
1. Чего конкретно ты этим хочешь добиться?
2. Что делает `inherit`?

2022-06-29 18:08 UTC, rasulovdev commented on style/colors.css
> +  --color-bg-btn: #f1f1f1;
А если я захочу этот цвет использовать не в кнопке?

2022-06-29 18:08 UTC, rasulovdev commented on style/colors.css
> +  --color-primary-bg: #5770fb;
Я ожидаю получить цвет `#304ffd` для фона при использовании `--color-primary-bg`

2022-06-29 18:08 UTC, rasulovdev commented on style/components/app-header.css
>    width: 1px;
Чет странное

2022-06-29 18:08 UTC, rasulovdev commented on style/components/badge.css
> +  --border-radius-sm: 6px;
Переменные из файлов `colors.css` и `fx.css` переназначать нельзя

2022-06-29 18:08 UTC, rasulovdev commented on style/components/badge.css
> +.badge.grey {
Мы не используем конкретные названия цветов

2022-06-29 18:08 UTC, rasulovdev commented on style/components/badge.css
> +  padding-left: 0.5rem;
И почему класс, который вроде бы должен относиться только к изменению цветов, меняет форму элемента?

2022-06-29 18:08 UTC, rasulovdev commented on style/components/button.css
> +}
А почему это здесь? У тебя форм контролом будет только кнопка?

2022-06-29 18:08 UTC, rasulovdev commented on style/components/button.css
>    transition: background-color var(--transition-duration);
Думаю цвет текста тоже нужно

2022-06-29 18:08 UTC, AzamatRasulov commented on style/colors.css
> +  --color-bg-btn: #f1f1f1;
В глобальных переменных мы не используем конкретных названий: ни цветов (красный, белый), ни положений (там, тут, вот для того)

2022-06-29 18:08 UTC, rasulovdev commented on style/components/app-header.css
> +    --container-padding-y: 0.3rem;
Шатаи хамира мехри дертар. Подумай, где и как

2022-06-29 18:08 UTC, AzamatRasulov commented on style/components/app-header.css
> +    margin-bottom: 0;
Почему?

2022-06-29 18:08 UTC, AzamatRasulov commented on style/components/button.css
> +.btn.no-bg {
Вот это вообще лишнее

2022-06-29 18:08 UTC, AzamatRasulov commented on style/components/horizontal-divider.css
> +}
Совсем не понимаю назначение этого компонента. Если ты хотел черту, я не вижу ее здесь

2022-06-29 18:08 UTC, AzamatRasulov commented on style/components/page.header.css
> +.page-header {
Странное **_название файла_**

2022-06-29 18:08 UTC, rasulovdev commented on style/fx.css
> +  --border-radius-button: 13px;
Ничего подобного

2022-06-29 18:08 UTC, AzamatRasulov commented on style/layout.css
> +  --container-padding-x: 1.2rem;
Почему не в руте?

2022-07-02 02:08 UTC, alisherj0n commented on style/components/badge.css
> +  --border-radius-sm: 6px;
Нужно создавать под нужды элемента ?

2022-07-02 16:49 UTC, alisherj0n commented on style/components/app-header.css
> +    margin-bottom: 0;
Ты писал, что на маленьких экранах размер и отступ сверу заголовка уменьшить

2022-07-02 17:02 UTC, alisherj0n commented on style/components/button.css
> +}
На даннои этапе да

2022-07-31 09:13 UTC, AzamatRasulov requested changes

2022-07-31 09:13 UTC, rasulovdev commented on style/components/button.css
> +  border-radius: 13px;
Вынести в переменную по аналогии с `form-control...`

2022-07-31 09:13 UTC, AzamatRasulov commented on style/components/button.css
> +  box-shadow: 0px 2px 0px 0px #263fca;
1. В таком случае высота кнопок получается разной,  Лучше сделать бордером
2. Не проработал все состояния. При **нажатии** цвет фона должен совпадать с цветом нижней грани, чтобы был эффект нажатия

2022-07-31 09:13 UTC, AzamatRasulov commented on index.html
> +          <div class="page-view">
Неправильная структура

2022-07-31 09:13 UTC, AzamatRasulov commented on index.html
> +            <button class="btn icon-only no-bg">
Лишний класс

2022-07-31 12:24 UTC, merged