10 project list projects grid
alisherj0n/rocket pull request #23
Opened 2022-08-01 07:22 UTC by alisherj0n

2022-08-01 07:51 UTC, AzamatRasulov requested changes

2022-08-01 07:51 UTC, AzamatRasulov commented on style/base.css
> +}
Ничего подобного

2022-08-01 07:51 UTC, AzamatRasulov commented on style/bundle.css
> +@import url(./components/customer-info.css);
Это что?

2022-08-01 07:51 UTC, AzamatRasulov commented on style/components/badge.css
> +}
Выше должно быть

2022-08-01 07:51 UTC, AzamatRasulov commented on style/components/project.css
> +.project {
Все-таки меня смущает это название. Пускай будет `project-list-item`

2022-08-01 07:51 UTC, AzamatRasulov commented on style/components/project.css
> +.project .header .btn {
`.btn` – базовый класс, нельзя его стилизовать отдельно

2022-08-01 07:51 UTC, AzamatRasulov commented on style/components/project.css
> +.project .header .btn {
И вообще, зачем тут развел через margin? По-моему можно по-обычному тут сделать

2022-08-01 07:51 UTC, AzamatRasulov commented on style/components/project.css
> +  max-width: 12rem;
Нельзя фикс значения указывать.

2022-08-01 07:51 UTC, AzamatRasulov commented on style/layout.css
> +}
Может лучше флексом?

2022-08-01 10:38 UTC, alisherj0n commented on style/components/project.css
> +  max-width: 12rem;
В этом случае можно ли задать ширину здесь 100%, а вот родителю уже фикс значение или в общем нельзя ?

2022-08-02 12:52 UTC, AzamatRasulov requested changes

2022-08-02 12:52 UTC, AzamatRasulov commented on style/components/badge.css
> +.badge.large.warning {
А если мне понадобится маленький бейдж с таким цветом?

2022-08-02 12:52 UTC, AzamatRasulov commented on style/components/mini-profile.css
> +  width: 100%;
`display: flex` по умолчанию разве не занимает всю доступную ширину?

2022-08-02 12:52 UTC, AzamatRasulov commented on style/components/mini-profile.css
> +  width: 100%;
То же самое

2022-08-02 12:52 UTC, AzamatRasulov commented on style/components/badge.css
> +.badge.large.danger {
то же самое

2022-08-02 12:52 UTC, AzamatRasulov commented on index.html
> +                  <span class="progress" style="width: 50%"></span>
Чиба span?

2022-08-02 12:52 UTC, AzamatRasulov commented on style/components/progress-bar.css
> +  display: block;
Агар span накни, хамирам даркор намеша

2022-08-02 12:52 UTC, AzamatRasulov commented on style/components/project-list-item.css
> +  flex-shrink: 0;
1. Это не относится к самой карточке.
2. Оно вообще нужно? Ты же эту карточку в гриде используешь

2022-08-02 12:52 UTC, AzamatRasulov commented on style/components/project-list-item.css
> +.project-list-item .progress-status {
Это вообще зачем?

2022-08-03 05:54 UTC, AzamatRasulov requested changes

2022-08-03 05:54 UTC, AzamatRasulov commented on index.html
> +              </small>
small?

2022-08-03 05:54 UTC, AzamatRasulov commented on index.html
> +                  alt=""
alt?

2022-08-03 05:54 UTC, AzamatRasulov commented on style/bundle.css
> +@import url(./components/avatar.css);
priority

2022-08-03 05:54 UTC, AzamatRasulov commented on style/bundle.css
> +@import url(./components/progress-bar.css);
priority

2022-08-03 07:18 UTC, AzamatRasulov approved these changes

2022-08-03 07:18 UTC, merged