#53-css-variables-to-scss
alisherj0n/rocket pull request #54
Opened 2022-10-13 09:00 UTC by alisherj0n

2022-10-13 09:23 UTC, AzamatRasulov requested changes

2022-10-13 09:23 UTC, AzamatRasulov commented on src/_base.scss
> +@use "./colors" as *;
What does `as *` do? Currently you're just making it work, without using the full advantage. Read the docs carefully about what it is used for and strictly follow the docs.

2022-10-13 09:23 UTC, AzamatRasulov commented on src/_colors.scss
> +$color-success-dark: #27b950;
In combination with **_correct_** use of `@use "..." as ...` we no longer need to prefix our variables with their type – `color-` in this case.

2022-10-13 09:23 UTC, AzamatRasulov commented on src/_base.scss
> +@use "./colors" as *;
Just read `@use "./colors" as *`. It is a plain english. You can tell what `as` keyword does right away.

2022-10-18 14:48 UTC, AzamatRasulov commented on src/_typography.scss
> +  color: map-get(colors.$color, "heading");
When you do maps, there's no need in namespaces. Don't be dumb to repeat the same mistake for 1234598023495 times. What else could you pull from `colors` if not `color`? It should be `map-get(colors, "heading")`. Same for all maps

2022-10-18 15:05 UTC, AzamatRasulov requested changes

2022-10-18 15:05 UTC, rasulovdev commented on src/_base.scss
> +  color: map-get(colors.$color, "body");
When you do maps, there's no need in namespaces. Don't be dumb to repeat the same mistake for 1234598023495 times. What else could you pull from colors if not color? It should be map-get(colors, "body"). Same for all maps.

2022-10-18 15:05 UTC, rasulovdev commented on src/_base.scss
> +  color: map-get(colors.$color, "body");
A map is a virtual file itself. You can combine all maps in a single file and call it `variables.scss` without the risk of leaking anything.

2022-10-18 15:05 UTC, rasulovdev commented on src/_colors.scss
> +$color: (
There isn't a single color

2022-10-18 15:05 UTC, rasulovdev commented on src/_fx.scss
> +);
This is bullshit. You just doubled the code size

2022-10-18 15:05 UTC, rasulovdev commented on src/_form-controls.scss
> +$height-sm: 2.25rem;
any thoughts?

2022-10-18 15:05 UTC, rasulovdev commented on src/_form-controls.scss
> +$height-sm: 2.25rem;
for lines 3-5

2022-10-18 15:05 UTC, rasulovdev commented on src/_layout.scss
> +$container-padding: 1.2rem;
<s>Make sure you're not using this var anywhere outside. If you do, then extract it into a higher level file, same as we discussed about form-controls vars being used in buttons</s>

YOU ARE USING IT OUTSIDE.

2022-10-18 15:05 UTC, rasulovdev commented on src/components/_app-header.scss
> +@use "../layout";
Bullshit.

2022-10-19 06:48 UTC, AzamatRasulov requested changes

2022-10-19 06:48 UTC, AzamatRasulov commented on src/_variables.scss
> +);
bullshit

2022-10-19 06:48 UTC, AzamatRasulov commented on src/_variables.scss
> +);
Why sizes' order is different in different maps?

2022-10-19 06:48 UTC, AzamatRasulov commented on src/_variables.scss
> +$transition-duration: 0.2s;
If you decided to do this, then why other **_shared_** vars are in different files?

2022-10-19 09:48 UTC, AzamatRasulov commented on src/_variables.scss
> +$transition-duration: 0.2s;
This is not resolved

2022-10-19 09:49 UTC, AzamatRasulov requested changes
🤦‍♂️

2022-10-19 15:11 UTC, AzamatRasulov requested changes

2022-10-19 15:11 UTC, AzamatRasulov commented on src/_variables.scss
> +  "height-lg": 3rem,
b

2022-10-19 15:11 UTC, AzamatRasulov commented on src/_variables.scss
> +  "height-lg": 3rem,
o

2022-10-19 15:11 UTC, AzamatRasulov commented on src/_variables.scss
> +  "height-lg": 3rem,
o

2022-10-19 15:11 UTC, AzamatRasulov commented on src/_variables.scss
> +  "height-lg": 3rem,
l

2022-10-19 15:11 UTC, AzamatRasulov commented on src/_variables.scss
> +  "height-lg": 3rem,
s

2022-10-19 15:11 UTC, AzamatRasulov commented on src/_variables.scss
> +  "height-lg": 3rem,
h

2022-10-19 15:11 UTC, AzamatRasulov commented on src/_variables.scss
> +  "height-lg": 3rem,
e

2022-10-19 15:11 UTC, AzamatRasulov commented on src/_variables.scss
> +  "height-lg": 3rem,
e

2022-10-19 15:11 UTC, AzamatRasulov commented on src/_variables.scss
> +  "height-lg": 3rem,
t

2022-10-24 10:04 UTC, AzamatRasulov requested changes

2022-10-24 10:04 UTC, AzamatRasulov commented on src/_variables.scss
> +$colors: (
Find and follow my previous comment about what variables should be extracted into this file.

**This comment is NOT related to colors.** You just ignored my prev comment, so I won't point the exact vars.

2022-10-24 10:04 UTC, AzamatRasulov commented on src/_variables.scss
> +  "height-lg": 3rem,
Bullshit. Season 1, Episode 4.

2022-10-24 10:48 UTC, AzamatRasulov requested changes

2022-10-24 10:48 UTC, AzamatRasulov commented on src/_variables.scss
> +$form-controls-padding-y-xl: 2rem;
I see e new episode of bullshit is coming...

2022-10-25 07:28 UTC, AzamatRasulov requested changes

2022-10-25 07:28 UTC, AzamatRasulov commented on src/_variables.scss
> +$form-controls-padding-x: 0.8rem;
Why have a map and a plain var for the same property?

2022-10-25 07:28 UTC, AzamatRasulov commented on src/_variables.scss
> +$container-padding-xl: 1.8rem;
?

2022-10-25 07:28 UTC, AzamatRasulov commented on src/_variables.scss
> +$container-padding-xl: 1.8rem;
54-55

2022-10-25 07:28 UTC, AzamatRasulov commented on src/_variables.scss
> +$font-family: "Poppins", sans-serif;
Why is this here?

2022-10-25 07:31 UTC, alisherj0n commented on src/_variables.scss
> +$font-family: "Poppins", sans-serif;
This var is used in several places like base, normalize and form-controls

2022-10-26 04:38 UTC, merged